spring:
  application:
    name: nequi
  main:
    allow-circular-references: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/franquicia_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MariaDBDialect
server:
  port: 8080
  servlet:
    context-path: /api/v1